/* device:       /project/CANVIEW4 */
/* device model: CANVIEW4 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_EVENT__SPLASH_C
#define INCLUDE__VT3_EVENT__SPLASH_C

#include "vt3_base.h"
#include "vt3_lang.h"
#include "vt3_images.h"
#include "vt3_fonts.h"
#include "vt3_POU_common.h"
#include "vt3_Disp__Splash.h"
#include "vt3_Event__Splash.h"
#include "vt3_extra.h"
#include "version_vt3_common.h"
#include "version_vt3_runtime.h"

/* timer event handler for screen: /project/CANVIEW4/Screens/Splash */
void vt3_event_ind_Splash(BYTE event)
{
	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/CANVIEW4/Screens/Splash
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: Splash */


/* timer event handler for indicator: /project/CANVIEW4/Screens/Splash/multibitmap 
 * runs every 200ms
 */
void vt3_event_ind_Splash_multibitmap(
	BYTE event, 
	vt3_indicator_MultiBitmap FARPTR ind)
{
	ind->currentValue = (((SINT)0));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/CANVIEW4/Screens/Splash/multibitmap
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: multibitmap */


#endif /* INCLUDE__VT3_EVENT__SPLASH_C */

/* end of file */
