/* device:       /project/CANVIEW4 */
/* device model: CANVIEW4 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_EVENT__MAIN_C
#define INCLUDE__VT3_EVENT__MAIN_C

#include "vt3_base.h"
#include "vt3_lang.h"
#include "vt3_images.h"
#include "vt3_fonts.h"
#include "vt3_POU_common.h"
#include "vt3_Disp__Main.h"
#include "vt3_Event__Main.h"
#include "vt3_extra.h"
#include "version_vt3_common.h"
#include "version_vt3_runtime.h"

/* timer event handler for screen: /project/CANVIEW4/Screens/Main */
void vt3_event_ind_Main(BYTE event)
{
	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/CANVIEW4/Screens/Main
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: Main */


/* timer event handler for indicator: /project/CANVIEW4/Screens/Main/simple_text 
 * runs every 200ms
 */
void vt3_event_ind_Main_simple_text(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(6) FAR _str = { 6, 6, "X-AXIS" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/CANVIEW4/Screens/Main/simple_text
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text */


/* timer event handler for indicator: /project/CANVIEW4/Screens/Main/simple_text_2 
 * runs every 200ms
 */
void vt3_event_ind_Main_simple_text_2(
	BYTE event, 
	vt3_indicator_SimpleText FARPTR ind)
{
	static const STRING(6) FAR _str = { 6, 6, "Y-AXIS" };
	ind->currentValue = (PSTRING)&_str;

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/CANVIEW4/Screens/Main/simple_text_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: simple_text_2 */


/* timer event handler for indicator: /project/CANVIEW4/Screens/Main/number 
 * runs every 100ms
 */
void vt3_event_ind_Main_number(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = ((degreeLat));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/CANVIEW4/Screens/Main/number
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: number */


/* timer event handler for indicator: /project/CANVIEW4/Screens/Main/number_2 
 * runs every 100ms
 */
void vt3_event_ind_Main_number_2(
	BYTE event, 
	vt3_indicator_Number FARPTR ind)
{
	ind->currentValue = ((degreeLong));

	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/CANVIEW4/Screens/Main/number_2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: number_2 */


#endif /* INCLUDE__VT3_EVENT__MAIN_C */

/* end of file */
