/* device:       /project/CANVIEW4 */
/* device model: CANVIEW4 */
/* this file has been generated automatically by vt3 - do not modify! */


#ifndef INCLUDE__VT3_EVENT__SCREENFRAME_C
#define INCLUDE__VT3_EVENT__SCREENFRAME_C

#include "vt3_base.h"
#include "vt3_lang.h"
#include "vt3_images.h"
#include "vt3_fonts.h"
#include "vt3_POU_common.h"
#include "vt3_Disp__ScreenFrame.h"
#include "vt3_Event__ScreenFrame.h"
#include "vt3_extra.h"
#include "version_vt3_common.h"
#include "version_vt3_runtime.h"

/* timer event handler for screen frame: /project/CANVIEW4/screen_frame */
void vt3_event_ind_screen_frame(BYTE event)
{
	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/CANVIEW4/screen_frame
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	}

} /* end of event code for indicator: screen_frame */


/* timer event handler for physical control: /project/CANVIEW4/screen_frame/key_F1 */
void vt3_event_ind_screen_frame_key_F1(
	BYTE event, 
	vt3_indicator_PhysicalKey FARPTR ind)
{
	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/CANVIEW4/screen_frame/key_F1
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	if (ind->eventDown)
	{
	    F1 = (TRUE);
	}
	else
	{
	    F1 = (FALSE);
	}
	
	 
	if (ind->pressedTime > 500)
	{
	    F1 = (FALSE);
	}
	
	}

} /* end of event code for indicator: key_F1 */


/* timer event handler for physical control: /project/CANVIEW4/screen_frame/key_F2 */
void vt3_event_ind_screen_frame_key_F2(
	BYTE event, 
	vt3_indicator_PhysicalKey FARPTR ind)
{
	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/CANVIEW4/screen_frame/key_F2
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	if (ind->eventDown)
	{
	    F2 = (TRUE);
	}
	else
	{
	    F2 = (FALSE);
	}
	 
	if (ind->pressedTime > 500)
	{
	    F2 = (FALSE);
	}
	
	}

} /* end of event code for indicator: key_F2 */


/* timer event handler for physical control: /project/CANVIEW4/screen_frame/key_F3 */
void vt3_event_ind_screen_frame_key_F3(
	BYTE event, 
	vt3_indicator_PhysicalKey FARPTR ind)
{
	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/CANVIEW4/screen_frame/key_F3
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	if (ind->eventDown)
	{
	    F3 = (TRUE);
	}
	else
	{
	    F3 = (FALSE);
	}
	 
	if (ind->pressedTime > 500)
	{
	    F3 = (FALSE);
	}
	
	}

} /* end of event code for indicator: key_F3 */


/* timer event handler for physical control: /project/CANVIEW4/screen_frame/key_F4 */
void vt3_event_ind_screen_frame_key_F4(
	BYTE event, 
	vt3_indicator_PhysicalKey FARPTR ind)
{
	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/CANVIEW4/screen_frame/key_F4
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	if (ind->eventDown)
	{
	    F4 = (TRUE);
	}
	else
	{
	    F4 = (FALSE);
	}
	 
	if (ind->pressedTime > 500)
	{
	    F4 = (FALSE);
	}
	
	}

} /* end of event code for indicator: key_F4 */


/* timer event handler for physical control: /project/CANVIEW4/screen_frame/key_F5 */
void vt3_event_ind_screen_frame_key_F5(
	BYTE event, 
	vt3_indicator_PhysicalKey FARPTR ind)
{
	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/CANVIEW4/screen_frame/key_F5
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
	if (ind->eventDown)
	{
	    F5 = (TRUE);
	}
	else
	{
	    F5 = (FALSE);
	}
	 
	if (ind->pressedTime > 500)
	{
	    F5 = (FALSE);
	}
	
	}

} /* end of event code for indicator: key_F5 */


/* timer event handler for physical indicator: /project/CANVIEW4/screen_frame/screen_backlight */
void vt3_event_ind_screen_frame_screen_backlight(
	BYTE event, 
	vt3_indicator_PhysicalIndicator FARPTR ind)
{
	/* Warning: the code below is generated by vt3.
	 * If you wish to make changes, please use vt3.
	 * 
	 *  node is:    /project/CANVIEW4/screen_frame/screen_backlight
	 * 
	 * Omitted: the list of replaced identifiers is very long
	 */
	{
	
		ind->currentValue = ((vBacklight));
	
	}

} /* end of event code for indicator: screen_backlight */


#endif /* INCLUDE__VT3_EVENT__SCREENFRAME_C */

/* end of file */
